let horoscopos = {
    "Capricornio": [
        "Hoy será un gran día para ti.",
        "Deberías evitar tomar decisiones importantes hoy.",
        "Capricornio, hoy te sentirás lleno de determinación y enfoque, listo para enfrentar cualquier desafío que se presente en tu camino. Aprovecha esta energía para avanzar en tus metas profesionales y alcanzar nuevos logros. En el ámbito personal, tu lealtad y dedicación fortalecerán tus relaciones más importantes. Mantén un equilibrio saludable entre el trabajo y el tiempo para ti mismo, ¡y verás cómo alcanzas el éxito en todas las áreas de tu vida!",
        "Hoy, Capricornio, te sentirás inspirado y lleno de creatividad, listo para dar vida a tus ideas más audaces. Tu determinación y perseverancia te llevarán a superar cualquier obstáculo que se interponga en tu camino. En el ámbito financiero, tus decisiones prudentes te permitirán construir una base sólida para tu futuro. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo cada día se llena de nuevas oportunidades!",
        "Capricornio, hoy te espera un día lleno de oportunidades para el crecimiento personal y profesional. Tu disciplina y tu ética de trabajo te ayudarán a alcanzar tus metas con facilidad. En el ámbito personal, tus relaciones se fortalecerán gracias a tu sinceridad y tu compromiso. Recuerda tomarte un tiempo para relajarte y recargar energías, ¡y verás cómo todo se alinea a tu favor!",
        "Hoy, Capricornio, te sentirás en armonía contigo mismo y con el mundo que te rodea. Tu determinación y tu capacidad para superar los desafíos te llevarán hacia el éxito en todas tus empresas. En el ámbito personal, tu lealtad y tu generosidad fortalecerán tus lazos afectivos. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo cada día te acerca más a tus sueños más grandes!",
        "Capricornio, hoy podrías sentirte abrumado por la presión de tus responsabilidades y compromisos. Es posible que te resulte difícil mantener el equilibrio entre el trabajo y tu vida personal, lo que podría generar tensiones en tus relaciones. En el ámbito financiero, evita tomar decisiones apresuradas y asegúrate de pensar cuidadosamente antes de actuar. A pesar de los desafíos, recuerda que tienes la fuerza y la determinación para superar cualquier obstáculo que se interponga en tu camino.",
        "Hoy, Capricornio, podrías encontrarte luchando contra la sensación de estancamiento en tu vida. Es posible que te resulte difícil encontrar la motivación para avanzar en tus metas, lo que podría generar frustración y ansiedad. En el ámbito personal, es importante que te comuniques abierta y honestamente con tus seres queridos para evitar malentendidos. Recuerda que cada desafío es una oportunidad para crecer y aprender, ¡así que mantén la fe en ti mismo y sigue adelante!",
        "Capricornio, hoy podrías sentirte agobiado por la sensación de estar atrapado en una rutina. Es posible que te resulte difícil encontrar la inspiración para seguir adelante, lo que podría afectar tu rendimiento en el trabajo y tus relaciones personales. En el ámbito financiero, es crucial que evites tomar decisiones impulsivas y que te enfoques en mantener un equilibrio saludable en tus gastos. A pesar de los desafíos, recuerda que tienes la fuerza interior para superar cualquier obstáculo que se presente en tu camino.",
        "Hoy, Capricornio, podrías enfrentarte a obstáculos inesperados que pondrán a prueba tu paciencia y tu determinación. Las tensiones en tus relaciones personales podrían aumentar, lo que podría generar conflictos y malentendidos. En el ámbito financiero, es importante que te mantengas firme en tus decisiones y que evites cualquier riesgo innecesario. Aunque te enfrentes a desafíos, recuerda que tienes la capacidad de encontrar soluciones creativas y superar cualquier adversidad que se presente en tu camino."
    ],
    "Acuario": [
        "Hoy te sentirás inspirado por las posibilidades ilimitadas que el futuro tiene para ofrecer. Tu mente innovadora y tu enfoque progresista te llevarán a nuevos horizontes de éxito y realización. En el ámbito personal, tu espíritu independiente y libre resonará con aquellos que te rodean. Dedica tiempo a nutrir tus relaciones más importantes, ¡y verás cómo florecen con amor y conexión!",
        "Hoy, Acuario, te sentirás lleno de energía y entusiasmo por las oportunidades que el día tiene para ofrecer. Tu capacidad para enfrentar los desafíos con audacia te llevará a alcanzar nuevas alturas de éxito y realización. En el ámbito personal, tus relaciones se fortalecerán gracias a tu autenticidad y tu honestidad. Recuerda mantener una mente abierta y flexible, ¡y verás cómo el universo te sorprende con nuevas aventuras y experiencias!",
        "Acuario, hoy te espera un día lleno de descubrimientos emocionantes y aventuras inesperadas. Tu curiosidad y tu ingenio te llevarán a explorar nuevos territorios y expandir tus horizontes. En el ámbito personal, tu espíritu libre y tu individualidad te harán destacar entre la multitud. Recuerda mantenerte fiel a ti mismo y seguir tus sueños con valentía, ¡y verás cómo el mundo se abre ante ti con infinitas posibilidades!",
        "Hoy, Acuario, sentirás una profunda conexión con el mundo que te rodea, inspirándote a hacer una diferencia positiva en la vida de los demás. Tu generosidad y tu compasión te llevarán a alcanzar nuevas alturas de éxito y realización. En el ámbito personal, tus relaciones se fortalecerán gracias a tu empatía y tu bondad. Dedica tiempo a cultivar tus pasiones y aspiraciones, ¡y verás cómo cada día te brinda nuevas oportunidades para crecer y prosperar!",
        "Acuario, hoy te sentirás lleno de entusiasmo y creatividad, listo para enfrentar cualquier desafío que se presente en tu camino. Tu mente brillante y tu espíritu innovador te llevarán a descubrir nuevas posibilidades y oportunidades emocionantes. En el ámbito personal, tu originalidad y autenticidad te harán destacar entre la multitud. Recuerda mantener una mente abierta y flexible, ¡y verás cómo el universo te sorprende con nuevas aventuras y experiencias!",
        "Hoy, Acuario, sentirás una profunda conexión con tu intuición y sabiduría interior. Tu mente aguda y tu enfoque te ayudarán a encontrar soluciones innovadoras a los desafíos que se presenten en tu camino. En el ámbito personal, tus relaciones se fortalecerán gracias a tu autenticidad y tu honestidad. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo cada día te acerca más a la realización de tus sueños más grandes!",
        "Acuario, hoy te espera un día lleno de oportunidades para el crecimiento personal y la expansión de tu mente. Tu curiosidad insaciable y tu ingenio te llevarán a explorar nuevos horizontes y a descubrir nuevas pasiones. En el ámbito personal, tu espíritu independiente y tu amor por la libertad te ayudarán a fortalecer tus relaciones más importantes. Recuerda seguir tu corazón y confiar en tu intuición, ¡y verás cómo el universo te guía hacia la felicidad y el éxito!",
        "Hoy, Acuario, sentirás una profunda conexión con la naturaleza y el cosmos, inspirándote a buscar la verdad y la sabiduría en todas las cosas. Tu mente abierta y tu espíritu compasivo te llevarán a encontrar la belleza en las pequeñas cosas de la vida. En el ámbito personal, tu generosidad y tu amor por los demás te ayudarán a fortalecer tus relaciones y a construir conexiones significativas. Recuerda mantener un equilibrio entre tu vida espiritual y tu vida cotidiana, ¡y verás cómo cada día te brinda nuevas oportunidades para crecer y evolucionar!"
    ],
    "Piscis": [
        "Hoy te sentirás conectado con tu intuición y comprensión emocional, lo que te permitirá brindar apoyo y consuelo a quienes te rodean. Tu empatía y sensibilidad fortalecerán tus relaciones personales, creando vínculos más profundos y significativos. En el ámbito creativo, tu imaginación florecerá, inspirándote a explorar nuevas formas de expresión artística. Recuerda nutrir tu bienestar emocional y encontrar el equilibrio entre dar y recibir amor.",
        "Hoy, Piscis, te sentirás inspirado por tu capacidad para soñar en grande y visualizar un futuro brillante. Tu imaginación y creatividad te llevarán a explorar nuevas posibilidades y aventuras. En el ámbito personal, tus relaciones se fortalecerán gracias a tu compasión y generosidad. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo tus sueños más grandes se hacen realidad!",
        "Piscis, hoy te espera un día lleno de magia y maravilla, donde te sentirás más conectado que nunca con el universo que te rodea. Tu sensibilidad y compasión te permitirán ver la belleza en las pequeñas cosas de la vida y apreciar cada momento. En el ámbito personal, tus relaciones se fortalecerán gracias a tu apertura y sinceridad. Recuerda confiar en tu intuición y seguir tu corazón, ¡y verás cómo el universo te guía hacia la felicidad y el éxito!",
        "Hoy, Piscis, sentirás una profunda sensación de paz y armonía en tu interior, lo que te permitirá enfrentar los desafíos con serenidad y gracia. Tu conexión con tu lado espiritual te guiará hacia nuevas perspectivas y entendimientos. En el ámbito personal, tus relaciones se fortalecerán gracias a tu comprensión y empatía. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo cada día te acerca más a la realización de tus sueños más grandes!",
        "Piscis, hoy podrías sentirte abrumado por tus emociones, lo que podría dificultar tu capacidad para tomar decisiones claras y objetivas. Es importante que te tomes un tiempo para cuidar tu bienestar emocional y encontrar formas saludables de expresar lo que sientes. En el ámbito personal, tus relaciones podrían verse afectadas por malentendidos y confusiones. Recuerda comunicarte abierta y honestamente con tus seres queridos para evitar conflictos innecesarios.",
        "Hoy, Piscis, podrías encontrarte luchando contra sentimientos de confusión e indecisión en tu vida. Es posible que te resulte difícil encontrar la dirección y el propósito en medio de la incertidumbre. En el ámbito personal, tus relaciones podrían enfrentar desafíos debido a tus propias dudas y inseguridades. Recuerda confiar en ti mismo y en tus habilidades para superar cualquier obstáculo que se presente en tu camino.",
        "Piscis, hoy podrías sentirte desconectado de tu intuición y guía interna, lo que podría dificultar tu capacidad para tomar decisiones importantes. Es importante que te tomes un tiempo para reconectar contigo mismo y encontrar la claridad que necesitas. En el ámbito personal, tus relaciones podrían verse afectadas por tu falta de comunicación y entendimiento. Recuerda expresar tus sentimientos de manera abierta y sincera, ¡y verás cómo todo se aclara!",
        "Hoy, Piscis, podrías encontrarte luchando contra sentimientos de ansiedad y preocupación, lo que podría afectar tu bienestar emocional y tu capacidad para disfrutar del presente. Es importante que te permitas sentir tus emociones y encontrar formas saludables de lidiar con ellas. En el ámbito personal, tus relaciones podrían verse afectadas por tus propias inseguridades y miedos. Recuerda que cada desafío es una oportunidad para crecer y aprender, ¡así que mantén la fe en ti mismo y sigue adelante!"
    ],
    "Aries": [
        "Hoy te sentirás lleno de energía y determinación, listo para conquistar cualquier desafío que se interponga en tu camino. Tu espíritu valiente y tu iniciativa te llevarán a nuevas alturas de éxito y realización. En el ámbito personal, tu pasión y entusiasmo contagiarán a quienes te rodean, inspirándolos a seguir tus pasos. Recuerda mantenerte fiel a ti mismo y seguir adelante con valentía, ¡y verás cómo cada día te acerca más a tus sueños más grandes!",
        "Hoy, Aries, sentirás una profunda sensación de confianza en ti mismo y en tus habilidades. Tu determinación y tu coraje te ayudarán a superar cualquier obstáculo que se presente en tu camino hacia el éxito. En el ámbito personal, tu espontaneidad y tu energía positiva te llevarán a crear momentos inolvidables con tus seres queridos. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo cada día te brinda nuevas oportunidades para crecer y prosperar!",
        "Aries, hoy te espera un día lleno de emocionantes aventuras y nuevas oportunidades. Tu espíritu audaz y tu capacidad para tomar decisiones rápidas te llevarán a explorar nuevos territorios y a conquistar nuevos desafíos. En el ámbito personal, tu carisma y tu energía magnética te harán destacar entre la multitud, atrayendo la admiración y el apoyo de quienes te rodean. Recuerda seguir tu instinto y confiar en tu intuición, ¡y verás cómo el universo conspira a tu favor para que alcances tus metas más ambiciosas!",
        "Hoy, Aries, sentirás una profunda conexión con tu propósito y tu pasión en la vida. Tu determinación y tu fuerza de voluntad te llevarán a superar cualquier obstáculo que se interponga en tu camino hacia el éxito. En el ámbito personal, tu sinceridad y tu honestidad te ayudarán a fortalecer tus relaciones más importantes. Dedica tiempo a cultivar tu bienestar físico y emocional, ¡y verás cómo cada día te acerca más a la realización de tus sueños más grandes!",
        "Aries, hoy podrías encontrarte luchando contra sentimientos de impaciencia y frustración, lo que podría dificultar tu capacidad para tomar decisiones claras y objetivas. Es importante que te tomes un momento para respirar hondo y encontrar la calma interior que necesitas. En el ámbito personal, tus relaciones podrían verse afectadas por malentendidos y conflictos. Recuerda comunicarte abierta y honestamente con tus seres queridos para evitar tensiones innecesarias.",
        "Hoy, Aries, podrías sentirte desafiado por la falta de progreso en tus metas y proyectos. Es posible que te resulte difícil mantener la motivación y la determinación en medio de la incertidumbre. En el ámbito personal, tus relaciones podrían enfrentar desafíos debido a tu propia irritabilidad y agresividad. Recuerda tomarte un tiempo para reflexionar y encontrar soluciones pacíficas a los problemas que puedan surgir.",
        "Aries, hoy podrías sentirte agotado por la sensación de estar constantemente en movimiento y bajo presión. Es importante que te permitas tomarte un momento para descansar y recargar energías. En el ámbito personal, tus relaciones podrían verse afectadas por tu falta de atención y compromiso. Recuerda que es importante dedicar tiempo y esfuerzo a cultivar tus conexiones más importantes, ¡así que no tengas miedo de pedir ayuda si la necesitas!",
        "Hoy, Aries, podrías sentirte frustrado por la falta de control sobre ciertas situaciones en tu vida. Es importante que recuerdes que no puedes controlar todo y que a veces es necesario dejar ir y confiar en el proceso. En el ámbito personal, tus relaciones podrían enfrentar desafíos debido a tu propia terquedad y obstinación. Recuerda ser flexible y estar abierto a compromisos, ¡y verás cómo todo se resuelve de la mejor manera posible!"
    ],
    "Tauro": [
        "Hoy es un buen día para pasar tiempo con seres queridos.",
        "Hoy es un buen día para cuidar de ti mismo y relajarte.",
        "Tauro, hoy te sentirás inspirado para disfrutar de las pequeñas cosas de la vida. Tu aprecio por la belleza y la comodidad te llevará a buscar momentos de paz y tranquilidad. En el ámbito personal, tu lealtad y tu generosidad fortalecerán tus relaciones más importantes. Dedica tiempo a nutrir tu bienestar físico y emocional, ¡y verás cómo cada día se llena de nuevas oportunidades!",
        "Hoy, Tauro, te sentirás en armonía con el mundo que te rodea, lo que te permitirá disfrutar de la estabilidad y la seguridad en todas las áreas de tu vida. Tu determinación y tu ética de trabajo te ayudarán a alcanzar tus metas con facilidad. En el ámbito personal, tus relaciones se fortalecerán gracias a tu sinceridad y tu compromiso. Recuerda tomarte un tiempo para relajarte y recargar energías, ¡y verás cómo todo fluye con suavidad en tu vida!",
        "Tauro, hoy podrías sentirte abrumado por la presión de tus responsabilidades y compromisos. Es posible que te resulte difícil mantener el equilibrio entre el trabajo y tu vida personal, lo que podría generar tensiones en tus relaciones. En el ámbito financiero, evita tomar decisiones apresuradas y asegúrate de pensar cuidadosamente antes de actuar. A pesar de los desafíos, recuerda que tienes la fuerza y la determinación para superar cualquier obstáculo que se interponga en tu camino.",
        "Hoy, Tauro, podrías encontrarte luchando contra la sensación de estancamiento en tu vida. Es posible que te resulte difícil encontrar la motivación para avanzar en tus metas, lo que podría generar frustración y ansiedad. En el ámbito personal, es importante que te comuniques abierta y honestamente con tus seres queridos para evitar malentendidos. Recuerda que cada desafío es una oportunidad para crecer y aprender, ¡así que mantén la fe en ti mismo y sigue adelante!",
        "Tauro, hoy podrías sentirte agobiado por la sensación de estar atrapado en una rutina. Es posible que te resulte difícil encontrar la inspiración para seguir adelante, lo que podría afectar tu rendimiento en el trabajo y tus relaciones personales. En el ámbito financiero, es crucial que evites tomar decisiones impulsivas y que te enfoques en mantener un equilibrio saludable en tus gastos. A pesar de los desafíos, recuerda que tienes la fuerza interior para superar cualquier obstáculo que se presente en tu camino.",
        "Hoy, Tauro, podrías enfrentarte a obstáculos inesperados que pondrán a prueba tu paciencia y tu determinación. Las tensiones en tus relaciones personales podrían aumentar, lo que podría generar conflictos y malentendidos. En el ámbito financiero, es importante que te mantengas firme en tus decisiones y que evites cualquier riesgo innecesario. Aunque te enfrentes a desafíos, recuerda que tienes la capacidad de encontrar soluciones creativas y superar cualquier adversidad que se presente en tu camino."
    ],
    "Géminis": [
        "Hoy tu ingenio estará en su punto más alto, permitiéndote resolver problemas con facilidad y encontrar soluciones creativas. Aprovecha esta agudeza mental para avanzar en tus proyectos y comunicarte de manera efectiva con los demás.",
        "En este día, la curiosidad innata de Géminis estará en su apogeo, impulsándote a explorar nuevos intereses y descubrir conocimientos fascinantes. Abraza esta sed de aprendizaje y permítete disfrutar de experiencias enriquecedoras que amplíen tu perspectiva.",
        "Tu habilidad para adaptarte a diversas situaciones será destacada hoy, lo que te permitirá navegar hábilmente a través de cualquier cambio o desafío que se presente. Confía en tu flexibilidad y confía en que puedes manejar cualquier obstáculo con gracia y determinación.",
        "La energía sociable y amigable de Géminis estará en su máximo esplendor, atrayendo conexiones positivas y momentos alegres en compañía de amigos y seres queridos. Aprovecha este día para fortalecer lazos y disfrutar de la compañía de aquellos que te rodean.",
        "La dispersión y la falta de enfoque podrían ser desafíos hoy, dificultando tu capacidad para completar tareas o mantener la concentración en un objetivo específico. Trata de organizar tus prioridades y mantener la disciplina para evitar sentirte abrumado.",
        "La indecisión podría obstaculizar el progreso de Géminis, haciendo que te sientas atrapado entre diferentes opciones o caminos a seguir. Tómate tu tiempo para reflexionar y tomar decisiones con confianza, evitando caer en la parálisis por análisis.",
        "La tendencia a la superficialidad podría llevarte a pasar por alto detalles importantes hoy, lo que podría conducir a malentendidos o errores en tus interacciones. Presta atención a la profundidad y la calidad en tus comunicaciones y decisiones.",
        "La inconstancia emocional de Géminis podría generar conflicto en tus relaciones interpersonales, ya que podrías cambiar de humor o actitud con facilidad. Procura ser consciente de tus emociones y comunicarte de manera clara y empática para evitar malentendidos."
    ],
    "Cancer": [
        "Cáncer, hoy tu intuición estará especialmente aguda, permitiéndote percibir y entender las emociones de los demás con claridad. Aprovecha esta sensibilidad para ofrecer apoyo y comprensión a aquellos que lo necesiten, fortaleciendo así tus vínculos emocionales.",
        "En este día, la creatividad de Cáncer estará en su máximo esplendor, inspirándote a expresarte de formas nuevas y emocionantes. Dedica tiempo a actividades artísticas o proyectos personales que te llenen de alegría y satisfacción.",
        "Cáncer, tu naturaleza protectora y compasiva brillará hoy, impulsándote a cuidar y nutrir a tus seres queridos de manera amorosa y desinteresada. Sé generoso con tu tiempo y atención, y encontrarás una profunda gratificación en hacer felices a los demás.",
        "Hoy, la conexión con tu hogar y tu familia será especialmente reconfortante para Cáncer, ofreciéndote un refugio seguro donde puedas recargar tus energías y encontrar consuelo. Dedica tiempo a cultivar un ambiente armonioso en tu espacio vital y sentirás una paz interior duradera.",
        "Cáncer, la tendencia a aferrarte al pasado podría obstaculizar tu progreso hoy, impidiéndote liberarte de viejos patrones o situaciones que ya no te sirven. Sé valiente y disponte a dejar ir aquello que te impide crecer y avanzar hacia un futuro más brillante.",
        "En este día, la susceptibilidad emocional de Cáncer podría llevarte a sentirte herido fácilmente por comentarios o situaciones aparentemente insignificantes. Trata de mantener la calma y la perspectiva, recordando que tus emociones no siempre reflejan la realidad objetiva.",
        "Cáncer, la tendencia a sobreproteger a los demás podría generar resentimiento o dependencia en tus relaciones interpersonales hoy. Permítete soltar el control y confiar en la capacidad de los demás para cuidar de sí mismos, fomentando así un crecimiento mutuo y saludable.",
        "Hoy, la nostalgia excesiva de Cáncer podría llevarte a idealizar el pasado y sentirte insatisfecho con el presente. Practica el mindfulness y la gratitud, centrándote en las bendiciones y oportunidades que te rodean en el aquí y ahora."
    ],
    "Leo": [
        "Leo, hoy tu confianza y carisma natural estarán en su punto más alto, atrayendo la atención y el respeto de los demás a donde quiera que vayas. Aprovecha esta energía magnética para liderar con determinación y lograr tus objetivos con éxito.",
        "En este día, la creatividad y el espíritu emprendedor de Leo estarán en su apogeo, inspirándote a perseguir tus pasiones y buscar nuevas oportunidades de crecimiento personal y profesional. Confía en tus instintos y arriésgate a seguir tus sueños más audaces.",
        "Leo, tu generosidad y generosidad de corazón serán especialmente valoradas hoy, ya que encontrarás satisfacción en brindar apoyo y alegría a aquellos que te rodean. Sé un faro de luz y esperanza para los demás, y verás cómo tus acciones reverberan con impacto positivo.",
        "Hoy, la determinación y el enfoque de Leo te permitirán superar cualquier obstáculo o desafío que se presente en tu camino hacia el éxito. Mantén la cabeza en alto y sigue adelante con valentía, sabiendo que estás destinado a brillar con luz propia.",
        "Leo, la tendencia al orgullo y la arrogancia podría ser tu mayor obstáculo hoy, alejándote de la colaboración y la cooperación con los demás. Recuerda que el verdadero liderazgo radica en la humildad y la capacidad de trabajar en equipo hacia un objetivo común.",
        "En este día, la impaciencia de Leo podría llevarte a tomar decisiones apresuradas o impulsivas, sin considerar completamente las consecuencias a largo plazo. Tómate el tiempo necesario para reflexionar y considerar todas las opciones antes de actuar.",
        "Leo, la necesidad de atención y reconocimiento constante podría dejarte vulnerable a la búsqueda de validación externa en lugar de cultivar una verdadera confianza en ti mismo. Encuentra tu valía intrínseca y no dependas del aplauso de los demás para sentirte completo.",
        "Hoy, la obstinación de Leo podría causar fricciones en tus relaciones personales, ya que podrías resistirte a ceder o comprometer en situaciones de conflicto. Practica la empatía y la flexibilidad, recordando que ceder no es signo de debilidad, sino de madurez emocional."
    ],
    "Virgo": [
        "Virgo, hoy tu enfoque meticuloso y tu atención al detalle te permitirán destacar en tu trabajo y en tus actividades diarias. Aprovecha esta precisión para avanzar hacia tus metas con determinación y eficiencia, sabiendo que cada paso que das te acerca más al éxito.",
        "En este día, la habilidad de Virgo para analizar y resolver problemas será especialmente aguda, permitiéndote encontrar soluciones prácticas y efectivas incluso en las situaciones más desafiantes. Confía en tu intelecto y en tu capacidad para enfrentar cualquier obstáculo que se presente en tu camino.",
        "Virgo, tu atención al bienestar físico y emocional estará en su punto más alto hoy, inspirándote a adoptar hábitos saludables y a cuidar tu cuerpo y tu mente con cariño y diligencia. Dedica tiempo a actividades que te nutran y te fortalezcan, y verás cómo tu energía y vitalidad se incrementan.",
        "Hoy, la humildad y la modestia de Virgo te permitirán ganarte el respeto y la admiración de los demás, ya que valorarás más la colaboración que el protagonismo individual. Sé un ejemplo de integridad y servicio, y verás cómo tu influencia positiva se extiende a tu alrededor.",
        "Virgo, la tendencia al perfeccionismo podría llevarte a sentirte abrumado por expectativas poco realistas, impidiéndote disfrutar plenamente del presente y celebrar tus logros. Permítete ser humano y aceptar que el progreso es más importante que la perfección absoluta.",
        "En este día, la crítica autoexigente de Virgo podría sabotear tu confianza y autoestima, haciéndote sentir inseguro respecto a tus habilidades y capacidades. Recuerda que todos cometemos errores y que el crecimiento personal viene de aprender de ellos, en lugar de castigarnos por ellos.",
        "Virgo, la preocupación excesiva por los detalles podría llevarte a perder de vista el panorama general y a estresarte innecesariamente por cosas que están fuera de tu control. Practica la atención plena y la aceptación de lo que no puedes cambiar, centrando tu energía en lo que sí puedes influir.",
        "Hoy, la tendencia de Virgo a preocuparse por el futuro podría generar ansiedad y temor ante lo desconocido, impidiéndote disfrutar del momento presente. Confía en tu capacidad para adaptarte a los desafíos que se presenten y recuerda que cada día trae consigo nuevas oportunidades de crecimiento y aprendizaje."
    ],
    "Libra": [
        "Libra, hoy tu carisma será contagioso, irradiando una energía positiva que iluminará tu entorno. Aprovecha este día para fortalecer tus lazos afectivos, compartiendo amor y alegría con tus seres queridos. En el ámbito financiero, tus decisiones sabias y estratégicas te conducirán hacia la prosperidad. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo florecen nuevas oportunidades en tu vida!",
        "Hoy, Libra, sentirás una profunda armonía en tu ser, lo que te permitirá manifestar tus deseos con facilidad. Tus relaciones personales se fortalecerán con gestos de amor y comprensión. En cuanto a tus finanzas, tu enfoque y determinación te llevarán hacia el éxito económico. Confía en tu intuición y sigue tu corazón en todas tus decisiones. ¡El universo conspira a tu favor para que alcances tus metas más ambiciosas!",
        "Libra, hoy te espera un día lleno de oportunidades y momentos felices. Tu encanto natural atraerá la atención de quienes te rodean, fortaleciendo tus relaciones interpersonales. En el ámbito financiero, tus habilidades para gestionar tus recursos te permitirán alcanzar la estabilidad y la seguridad económica. Recuerda cuidar tu bienestar físico y emocional, ¡y verás cómo cada día brilla con nuevas posibilidades!",
        "Hoy, Libra, podrías sentirte abrumado por la indecisión y la incertidumbre en tu vida. Las tensiones en tus relaciones personales podrían alcanzar su punto máximo, generando conflictos y malentendidos. Es importante que te tomes un momento para reflexionar y encontrar la paz interior. En cuanto a tus finanzas, evita tomar decisiones impulsivas y sé prudente con tus gastos. Aunque el camino parezca difícil, recuerda que cada desafío te hace más fuerte.",
        "Libra, hoy podrías encontrarte luchando contra obstáculos que parecen insuperables. Las tensiones en tus relaciones personales podrían causar estrés y ansiedad, así que trata de mantener la calma y la compostura. En el ámbito financiero, es crucial que te mantengas firme en tus decisiones y evites cualquier riesgo innecesario. A pesar de los desafíos, recuerda que tienes la fuerza y la determinación para superar cualquier adversidad que se presente en tu camino.",
        "Libra, hoy te espera un día lleno de armonía y equilibrio. Tu capacidad para encontrar soluciones pacíficas en situaciones conflictivas te permitirá fortalecer tus relaciones interpersonales. En el ámbito financiero, tu enfoque y disciplina te ayudarán a alcanzar tus metas económicas. Dedica tiempo a cuidar tu bienestar físico y emocional, ¡y verás cómo todo fluye con facilidad en tu vida!",
        "Hoy, Libra, tu encanto natural estará en su punto más alto, atrayendo la atención y la admiración de quienes te rodean. Aprovecha este día para expresar tu creatividad y tu pasión en todo lo que hagas. En el ámbito financiero, tus decisiones inteligentes te llevarán hacia la prosperidad y el éxito. Confía en tu intuición y sigue tu corazón en todas tus acciones. ¡El universo está conspirando a tu favor para que logres tus sueños más grandes!",
        "Libra, hoy podrías sentirte desanimado por las tensiones en tus relaciones personales. Los conflictos y malentendidos podrían empañar tu día, así que trata de mantener la calma y la compostura. En el ámbito financiero, es importante que evites tomar decisiones impulsivas y que te centres en mantener un equilibrio saludable en tus gastos. Aunque te enfrentes a desafíos, recuerda que cada obstáculo es una oportunidad para crecer y aprender.",
        "Hoy, Libra, podrías encontrarte luchando contra la sensación de estancamiento en tu vida. Es posible que te resulte difícil encontrar la motivación para avanzar en tus metas, lo que podría generar frustración y ansiedad. En el ámbito personal, es importante que te comuniques abierta y honestamente con tus seres queridos para evitar malentendidos. Recuerda que cada desafío es una oportunidad para crecer y aprender, ¡así que mantén la fe en ti mismo y sigue adelante!",
        "Libra, hoy podrías sentirte agobiado por la sensación de estar atrapado en una rutina. Es posible que te resulte difícil encontrar la inspiración para seguir adelante, lo que podría afectar tu rendimiento en el trabajo y tus relaciones personales. En el ámbito financiero, es crucial que evites tomar decisiones impulsivas y que te enfoques en mantener un equilibrio saludable en tus gastos. A pesar de los desafíos, recuerda que tienes la fuerza interior para superar cualquier obstáculo que se presente en tu camino.",
        "Hoy, Libra, podrías enfrentarte a obstáculos inesperados que pondrán a prueba tu paciencia y tu determinación. Las tensiones en tus relaciones personales podrían aumentar, lo que podría generar conflictos y malentendidos. En el ámbito financiero, es importante que te mantengas firme en tus decisiones y que evites cualquier riesgo innecesario. Aunque te enfrentes a desafíos, recuerda que tienes la capacidad de encontrar soluciones creativas y superar cualquier adversidad que se presente en tu camino."
    ],
    "Escorpio": [
        "Escorpio, hoy tu determinación y pasión ardiente te llevarán a conquistar nuevos desafíos con coraje y resolución. Aprovecha esta energía intensa para perseguir tus metas con firmeza, sabiendo que tu poder interior te guiará hacia el éxito.",
        "En este día, la intuición profunda de Escorpio estará en su máximo esplendor, permitiéndote percibir verdades ocultas y entender las emociones más profundas, tanto en ti mismo como en los demás. Confía en tu instinto y síguelo fielmente, ya que te conducirá hacia caminos de transformación y crecimiento personal.",
        "Escorpio, tu magnetismo y carisma serán irresistibles hoy, atrayendo la atención y el respeto de quienes te rodean. Aprovecha esta influencia para inspirar a otros con tu fuerza interior y para crear conexiones significativas basadas en la autenticidad y la verdad.",
        "Hoy, la capacidad de Escorpio para regenerarse y renacer de las cenizas será destacada, permitiéndote dejar atrás el pasado y abrirte a nuevas oportunidades y experiencias. Permítete soltar aquello que ya no te sirve y abraza el potencial transformador del presente.",
        "Escorpio, la tendencia a la posesividad y los celos podría generar tensiones en tus relaciones interpersonales hoy, ya que podrías sentirte amenazado por la presencia de terceros en la vida de tus seres queridos. Confía en la fortaleza de tus lazos y cultiva la confianza mutua para superar estos desafíos.",
        "En este día, la tendencia de Escorpio a ser reservado y misterioso podría generar desconfianza o malentendidos en tus relaciones personales, ya que podrías mantener secretos o guardar información importante para ti mismo. Recuerda que la comunicación abierta y honesta es esencial para construir relaciones sólidas y duraderas.",
        "Escorpio, la intensidad emocional podría abrumarte hoy, llevándote a experimentar altibajos emocionales y reacciones impulsivas. Practica la autoconciencia y el autocontrol, permitiéndote procesar tus sentimientos de manera saludable y encontrar equilibrio en medio de la tormenta emocional.",
        "Hoy, la tendencia de Escorpio a aferrarse al resentimiento y la venganza podría obstaculizar tu crecimiento personal y tu bienestar emocional, ya que podrías estar demasiado enfocado en los agravios del pasado. Practica el perdón y la compasión, liberándote del peso del rencor y abriendo espacio para la sanación y el crecimiento interior."
    ],
    "Sagitario": [
        "Sagitario, hoy tu espíritu aventurero estará en su apogeo, impulsándote a buscar nuevas experiencias y horizontes más amplios. Aprovecha esta energía optimista para embarcarte en emocionantes aventuras y expandir tus límites, descubriendo así nuevas pasiones y oportunidades.",
        "En este día, la sinceridad y franqueza de Sagitario serán tus mayores aliados, permitiéndote comunicarte con autenticidad y claridad en todas tus interacciones. Confía en tu capacidad para expresar tu verdad con confianza y apertura, cultivando así relaciones basadas en la honestidad y la confianza mutua.",
        "Sagitario, tu optimismo contagioso será una fuente de inspiración para quienes te rodean hoy, infundiendo alegría y positividad en cada situación que encuentres. Aprovecha esta energía elevada para animar a los demás y para enfocarte en el lado brillante de la vida, incluso en los momentos más desafiantes.",
        "Hoy, la búsqueda de la verdad y el conocimiento será una prioridad para Sagitario, inspirándote a explorar nuevas ideas y filosofías que amplíen tu comprensión del mundo. Dedica tiempo a la reflexión y la contemplación, permitiéndote crecer y evolucionar a través del aprendizaje continuo.",
        "Sagitario, la tendencia a la imprudencia y la impulsividad podría llevarte a tomar decisiones apresuradas o arriesgadas hoy, sin considerar completamente las consecuencias a largo plazo. Toma un momento para reflexionar y evaluar cuidadosamente tus opciones antes de actuar, evitando así arrepentimientos innecesarios.",
        "En este día, la falta de compromiso y la aversión al compromiso podrían generar conflictos en tus relaciones personales y profesionales, ya que podrías resistirte a comprometerte completamente con una causa o un proyecto. Practica la flexibilidad y la apertura a nuevas experiencias, permitiéndote crecer y expandir tus horizontes.",
        "Sagitario, la tendencia a la imprudencia y la falta de atención a los detalles podrían causar problemas en tus actividades cotidianas hoy, haciéndote cometer errores o descuidar responsabilidades importantes. Mantén la calma y la concentración, y verifica tus acciones antes de proceder, para evitar contratiempos innecesarios.",
        "Hoy, la arrogancia y la tendencia a sobreestimar tus habilidades podrían llevarte a meterte en problemas o a enfrentarte a situaciones desafiantes que podrías haber evitado con un enfoque más humilde. Mantén los pies en la tierra y reconoce tus límites, permitiéndote aprender y crecer de manera más efectiva."
    ],
}
function agregarHoroscopo(signo, horoscopo) {
    horoscopos[signo].push(horoscopo);
}

function obtenerHoroscopo(signo) {
    let horoscoposSigno = horoscopos[signo];
    let indiceAleatorio = Math.floor(Math.random() * horoscoposSigno.length);
    return horoscoposSigno[indiceAleatorio];
}

let handler = (m, { command, text }) => {
    if (!text) throw `Ejemplo: ${command} 2003 02 25`

    const [year, month, day] = text.match(/\d+/g).map(Number)
    const date = new Date(year, month - 1, day)

    if (isNaN(date)) throw `Fecha inválida, por favor usa el siguiente formato: AAAA MM DD. Por ejemplo: ${command} 2003 02 25`

    const today = new Date()
    const currentYear = today.getFullYear()
    const currentMonth = today.getMonth() + 1
    const currentDay = today.getDate()

    const birth = [year, month, day]
    const horoscopo = obtenerHoroscopo(getZodiac(month, day))

    const ageD = new Date(today - date)
    const age = ageD.getFullYear() - new Date(1970, 0, 1).getFullYear()

    const isBirthday = month === currentMonth && day === currentDay
    const ageText = isBirthday ? `${age} - ¡Feliz cumpleaños! 🥳` : age

    const replyText = `
Fecha de nacimiento: ${birth.join('-')}
Edad: ${ageText}
Signo horóscopo: ${getZodiac(month, day)}
Horóscopo: ${horoscopo}
`.trim()

    m.reply(replyText)
}

handler.help = ['horóscopo <AAAA MM DD>']
handler.tags = ['tools']
handler.command = /^hor[oó]scopo$/i

const zodiak = [
    ["Capricornio", new Date(1970, 0, 1)],
    ["Acuario", new Date(1970, 0, 20)],
    ["Piscis", new Date(1970, 1, 19)],
    ["Aries", new Date(1970, 2, 21)],
    ["Tauro", new Date(1970, 3, 21)],
    ["Geminis", new Date(1970, 4, 21)],
    ["Cancer", new Date(1970, 5, 22)],
    ["Leo", new Date(1970, 6, 23)],
    ["Virgo", new Date(1970, 7, 23)],
    ["Libra", new Date(1970, 8, 23)],
    ["Scorpion", new Date(1970, 9, 23)],
    ["Sagitario", new Date(1970, 10, 22)],
    ["Capricornio", new Date(1970, 11, 22)]
].reverse()

function getZodiac(month, day) {
    let d = new Date(1970, month - 1, day)
    return zodiak.find(([_, _d]) => d >= _d)[0]
}

export default handler
